### ISSUE TITLE
kwin windows rules are ignored

### ISSUE THREAD

**Issue by fabianski7** [d86leader/dynamic_workspaces#6]
To reproduce
1. Create three workspaces
2. Create a rule to force a window into workspace 3
3. Visit the first workspace

The window will be moved to the second workspace as soon as the active workspace is the first.

**Comment by d86leader** [comment]
That's fun. It even overwrites the "force" option, and moves the window to the righmost non-empty desktop. However, when the third desktop is created, the window would be forced into it, so I don't see much of a problem.

What in you opinion is supposed to happen in the case with window rules? I think current behaviour is ok.
